export const LOADING = 'LOADING';

export const LOGIN_ERROR = 'LOGIN_ERROR';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const CREATE_ERROR = 'CREATE_ERROR';
export const CREATE_SUCCESS = 'CREATE_SUCCESS';
export const REMOVE_SUCCESS = 'REMOVE_SUCCESS';
